/**:
    ros__parameters:
      ndt_resolution: 1.0
      ndt_step_size: 0.1
      ndt_num_threads: 1
      ndt_max_iterations: 500
      transform_epsilon: 0.0005
      voxel_leaf_size: 0.2
      scan_max_range: 30.0
      scan_min_range: 0.1
      scan_period: 0.1
      use_pcd_map: true
      map_path: "/home/ada1/ros2_ws/map/map.pcd"
      set_initial_pose: true
      initial_pose_x: 0.0
      initial_pose_y: 0.0
      initial_pose_z: 0.0
      initial_pose_qx: 0.0
      initial_pose_qy: 0.0
      initial_pose_qz: 0.0
      initial_pose_qw: 1.0
      enable_debug: false
      global_frame_id: map
      base_frame_id: base_link
